name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build the application
        uses: ./.github/actions/build

      - name: Get tag name
        id: tag
        uses: olegtarasov/get-tag@v2.1

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/libs/CoreO8-${{ steps.tag.outputs.tag  }}.jar
          body: "# CoreO8 ${{ steps.tag.outputs.tag  }}"